const thing = {
  subscription: {
    id: "sub_1QNTcCLJih1LMxtD592EWsjX",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
      liability: null,
    },
    billing_cycle_anchor: 1733465504,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1732169504,
    currency: "usd",
    current_period_end: 1733465504,
    current_period_start: 1732169504,
    customer: "cus_RFzbiW4wNqJPCO",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    ended_at: null,
    invoice_settings: {
      account_tax_ids: null,
      issuer: {
        type: "self",
      },
    },
    items: {
      object: "list",
      data: [
        {
          id: "si_RFzbI8Pn0nvLRl",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1732169505,
          discounts: [],
          metadata: {},
          plan: {
            id: "price_1QLtsMLJih1LMxtDe2I415Iy",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 6999,
            amount_decimal: "6999",
            billing_scheme: "per_unit",
            created: 1731793794,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_REMbE9d7qHTJHh",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1QLtsMLJih1LMxtDe2I415Iy",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1731793794,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_REMbE9d7qHTJHh",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 6999,
            unit_amount_decimal: "6999",
          },
          quantity: 1,
          subscription: "sub_1QNTcCLJih1LMxtD592EWsjX",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1QNTcCLJih1LMxtD592EWsjX",
    },
    latest_invoice: {
      id: "in_1QNTcCLJih1LMxtDqDgBrncG",
      object: "invoice",
      account_country: "US",
      account_name: "EZ Plans",
      account_tax_ids: null,
      amount_due: 0,
      amount_paid: 0,
      amount_remaining: 0,
      amount_shipping: 0,
      application: null,
      application_fee_amount: null,
      attempt_count: 0,
      attempted: true,
      auto_advance: false,
      automatic_tax: {
        enabled: false,
        liability: null,
        status: null,
      },
      automatically_finalizes_at: null,
      billing_reason: "subscription_create",
      charge: null,
      collection_method: "charge_automatically",
      created: 1732169504,
      currency: "usd",
      custom_fields: null,
      customer: "cus_RFzbiW4wNqJPCO",
      customer_address: null,
      customer_email: "justindanielclark@gmail.com",
      customer_name: null,
      customer_phone: null,
      customer_shipping: null,
      customer_tax_exempt: "none",
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: null,
      effective_at: 1732169504,
      ending_balance: 0,
      footer: null,
      from_invoice: null,
      hosted_invoice_url:
        "https://invoice.stripe.com/i/acct_1QKrfRLJih1LMxtD/test_YWNjdF8xUUtyZlJMSmloMUxNeHRELF9SRnpiZ0JrZ1RrSmlPcFVIZkY1Z21lM2YwdUNGdE1KLDEyMjcxMDMwNQ0200Zj3Vs2WR?s=ap",
      invoice_pdf:
        "https://pay.stripe.com/invoice/acct_1QKrfRLJih1LMxtD/test_YWNjdF8xUUtyZlJMSmloMUxNeHRELF9SRnpiZ0JrZ1RrSmlPcFVIZkY1Z21lM2YwdUNGdE1KLDEyMjcxMDMwNQ0200Zj3Vs2WR/pdf?s=ap",
      issuer: {
        type: "self",
      },
      last_finalization_error: null,
      latest_revision: null,
      lines: {
        object: "list",
        data: [
          {
            id: "il_1QNTcCLJih1LMxtDGmWnESkX",
            object: "line_item",
            amount: 0,
            amount_excluding_tax: 0,
            currency: "usd",
            description: "Trial period for Pro Plan",
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice: "in_1QNTcCLJih1LMxtDqDgBrncG",
            livemode: false,
            metadata: {},
            period: {
              end: 1733465504,
              start: 1732169504,
            },
            plan: {
              id: "price_1QLtsMLJih1LMxtDe2I415Iy",
              object: "plan",
              active: true,
              aggregate_usage: null,
              amount: 6999,
              amount_decimal: "6999",
              billing_scheme: "per_unit",
              created: 1731793794,
              currency: "usd",
              interval: "month",
              interval_count: 1,
              livemode: false,
              metadata: {},
              meter: null,
              nickname: null,
              product: "prod_REMbE9d7qHTJHh",
              tiers_mode: null,
              transform_usage: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            pretax_credit_amounts: [],
            price: {
              id: "price_1QLtsMLJih1LMxtDe2I415Iy",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731793794,
              currency: "usd",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: "prod_REMbE9d7qHTJHh",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "unspecified",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 6999,
              unit_amount_decimal: "6999",
            },
            proration: false,
            proration_details: {
              credited_items: null,
            },
            quantity: 1,
            subscription: "sub_1QNTcCLJih1LMxtD592EWsjX",
            subscription_item: "si_RFzbI8Pn0nvLRl",
            tax_amounts: [],
            tax_rates: [],
            type: "subscription",
            unit_amount_excluding_tax: "0",
          },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/invoices/in_1QNTcCLJih1LMxtDqDgBrncG/lines",
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: "43DF81D3-0001",
      on_behalf_of: null,
      paid: true,
      paid_out_of_band: false,
      payment_intent: null,
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: null,
      },
      period_end: 1732169504,
      period_start: 1732169504,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering: null,
      shipping_cost: null,
      shipping_details: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: "paid",
      status_transitions: {
        finalized_at: 1732169504,
        marked_uncollectible_at: null,
        paid_at: 1732169504,
        voided_at: null,
      },
      subscription: "sub_1QNTcCLJih1LMxtD592EWsjX",
      subscription_details: {
        metadata: {},
      },
      subtotal: 0,
      subtotal_excluding_tax: 0,
      tax: null,
      test_clock: null,
      total: 0,
      total_discount_amounts: [],
      total_excluding_tax: 0,
      total_pretax_credit_amounts: [],
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: null,
    },
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: "on_subscription",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: "seti_1QNTcDLJih1LMxtDS2jF1dTa",
    pending_update: null,
    plan: {
      id: "price_1QLtsMLJih1LMxtDe2I415Iy",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 6999,
      amount_decimal: "6999",
      billing_scheme: "per_unit",
      created: 1731793794,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      meter: null,
      nickname: null,
      product: "prod_REMbE9d7qHTJHh",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1732169504,
    status: "trialing",
    test_clock: null,
    transfer_data: null,
    trial_end: 1733465504,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: 1732169504,
  },
};
